/** Still required due to AGCP plugin. */
buildscript {
    repositories {
        maven {url 'https://developer.huawei.com/repo/'}
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.3.2'
        classpath 'com.huawei.agconnect:agcp:1.9.3.302'
    }
}

plugins {
    id 'com.android.application' version '8.3.2' apply false
    id 'com.android.library' version '8.3.2' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.23' apply false
//    id "com.huawei.agconnect.agcp" version "1.7.3.302" apply false
//    id "com.huawei.agconnect.apms" version "1.6.1.300" apply false
}


