plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
    id 'kotlin-parcelize'
    id 'com.huawei.agconnect'
}

android {
    namespace 'com.scheartmed.push'
    compileSdk project.properties['TARGET_SDK'].toInteger()

    defaultConfig {
        minSdkVersion project.properties['MIN_SDK'].toInteger()
        targetSdk project.properties['TARGET_SDK'].toInteger()
        versionCode project.properties['APP_VERSION_CODE'].toInteger()
        versionName project.properties['APP_VERSION_NAME']

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }


}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    api "com.netease.nimlib:push:10.9.10"
    api "com.netease.nimlib:basesdk:10.9.10"

    api("com.huawei.hms:push:6.10.0.300")
    api('com.huawei.agconnect:agconnect-core:1.9.1.302')

}