plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt'
    id 'kotlin-parcelize'
}


android {
    namespace "com.mou.mvvmmodule" // 新版必须指定
    compileSdk project.properties['TARGET_SDK'].toInteger()
    defaultConfig {
        minSdkVersion project.properties['MIN_SDK'].toInteger()
        targetSdk project.properties['TARGET_SDK'].toInteger()
        versionCode project.properties['APP_VERSION_CODE'].toInteger()
        versionName project.properties['APP_VERSION_NAME']
        multiDexEnabled true
        ndk { //设置支持的SO库架构（开发者可以根据需要，选择一个或多个平台的so）
            abiFilters "armeabi-v7a", "arm64-v8a"
        }

    }

    buildFeatures {
        buildConfig = true
        viewBinding = true
    }

    signingConfigs {
        debug {
            keyAlias 'heartmed'
            keyPassword 'hrt2025'
            storeFile file("./hrt.jks")
            storePassword 'hrt2025'
        }
        release {
            keyAlias 'heartmed'
            keyPassword 'hrt2025'
            storeFile file("./hrt.jks")
            storePassword 'hrt2025'
        }
    }


    buildTypes {
        debug {
            buildConfigField "boolean", "LOG_DEBUG", "true"
            minifyEnabled false
            shrinkResources false
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
        }
        release {
            buildConfigField "boolean", "LOG_DEBUG", "false"
            //是否开启混淆
            minifyEnabled true
            // 移除无用的resource文件
            shrinkResources false
            // Zipalign优化
            zipAlignEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

//开启databinding
    dataBinding {
        enabled = false
    }

//生成libs目录
    sourceSets {
        main.jniLibs.srcDirs = ['libs']
    }

    lint {
        abortOnError = false
        checkReleaseBuilds = false
        textReport = false
        textOutput = file("lint-report.txt")
        // 可选：配置报告类型
        htmlReport = true
        htmlOutput = file("$buildDir/reports/lint/lint.html")
    }

    flavorDimensions "env"
    productFlavors {
        dev {
            dimension "env"
            buildConfigField "String", "BASE_URL", "\"https://dev.api.example.com/\""
            buildConfigField "String", "ENV_TYPE", "\"dev\""
        }

        qa {   // 用 qa 或 staging 代替 test
            dimension "env"
            buildConfigField "String", "BASE_URL", "\"https://qa.api.example.com/\""
            buildConfigField "String", "ENV_TYPE", "\"qa\""
        }

        uta {
            dimension "env"
            buildConfigField "String", "BASE_URL", "\"https://pre.api.example.com/\""
            buildConfigField "String", "ENV_TYPE", "\"uta\""
        }

        prod {
            dimension "env"
            buildConfigField "String", "BASE_URL", "\"https://api.example.com/\""
            buildConfigField "String", "ENV_TYPE", "\"prod\""
        }
    }


}

android.applicationVariants.configureEach { variant ->
    variant.outputs.each { output ->
        def flavor = variant.flavorName
        def versionName = variant.versionName
        def time = new Date().format("MMdd_HH:mm")
        output.outputFileName = "heartmed_v${versionName}_${time}(${flavor}).apk"
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.20"
    implementation project(':core_common')
    implementation project(':core_network')
    implementation project(':feature_im')
    implementation project(':feature_business')

}