plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'kotlin-kapt'
}
android {
    compileSdkVersion rootProject.ext.android["compileSdkVersion"]
    buildToolsVersion rootProject.ext.android["buildToolsVersion"]

    compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion rootProject.ext.android["minSdkVersion"]
        targetSdkVersion rootProject.ext.android["targetSdkVersion"]
        versionCode rootProject.ext.android["versionCode"]
        versionName rootProject.ext.android["versionName"]
    }
    dataBinding {
        enabled = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${versions["kotlin_version"]}"
    api "androidx.appcompat:appcompat:${versions["appcompatVersion"]}"
    api "androidx.legacy:legacy-support-v4:${versions["appcompatVersion"]}"
    api "com.google.android.material:material:${versions["appcompatVersion"]}"
    api "androidx.recyclerview:recyclerview:${versions["recyclerviewVersion"]}"
    api "androidx.annotation:annotation:${versions["appcompatVersion"]}"

    //mvvm
    kapt "androidx.lifecycle:lifecycle-compiler:${versions["lifeVersion"]}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:${versions["lifeVersion"]}"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:${versions["lifeVersion"]}"

    //rxjava
    api "io.reactivex.rxjava2:rxandroid:2.0.2"
    api "io.reactivex.rxjava2:rxjava:2.1.12"
    api "com.uber.autodispose:autodispose:0.8.0"
    api "com.uber.autodispose:autodispose-android-archcomponents:0.8.0"

    //network
    api "com.squareup.retrofit2:retrofit:${versions["retrofitSdkVersion"]}"
    api "com.squareup.retrofit2:converter-gson:${versions["retrofitSdkVersion"]}"
    api "com.squareup.retrofit2:adapter-rxjava2:${versions["retrofitSdkVersion"]}"
    api "com.squareup.okhttp3:okhttp:${versions["okhttp3Version"]}"
    api "com.squareup.okhttp3:logging-interceptor:3.9.0"
    api "com.github.bumptech.glide:glide:${versions["glideSdkVersion"]}"
    api "jp.wasabeef:glide-transformations:2.0.1"
    api "com.google.code.gson:gson:2.8.2"
    api "com.github.franmontiel:PersistentCookieJar:v1.0.1"

    //tools
    api "com.orhanobut:logger:2.2.0"
    api 'androidx.multidex:multidex:2.0.0'
    api "com.blankj:utilcodex:1.31.0"
}
