plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.kapt' // 如果使用注解处理器
    id 'kotlin-parcelize'
}

android {
    namespace "com.mou.basemvvm"
    compileSdk 34
    defaultConfig {
        minSdkVersion 21
        targetSdk 34
        versionCode 1000
        versionName "1000"
    }
    buildFeatures {
        buildConfig = true
        viewBinding = true
    }
    dataBinding {
        enabled = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.20"
    api "androidx.appcompat:appcompat:1.7.1"
    api "androidx.legacy:legacy-support-v4:1.0.0"
    api "com.google.android.material:material:1.12.0"
    api "androidx.recyclerview:recyclerview:1.2.0"
    api "androidx.annotation:annotation:1.0.0"

    //mvvm
    kapt "androidx.lifecycle:lifecycle-compiler:2.9.2"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.9.2"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:2.9.2"

    //rxjava
    api "io.reactivex.rxjava2:rxandroid:2.0.2"
    api "io.reactivex.rxjava2:rxjava:2.1.12"
    api "com.uber.autodispose:autodispose:0.8.0"
    api "com.uber.autodispose:autodispose-android-archcomponents:0.8.0"

    //network
    api "com.squareup.retrofit2:retrofit:2.9.0"
    api "com.squareup.retrofit2:converter-gson:2.9.0"
    api "com.squareup.retrofit2:adapter-rxjava2:2.9.0"
    api "com.squareup.okhttp3:okhttp:3.10.0"
    api "com.squareup.okhttp3:logging-interceptor:3.9.0"
    api "com.github.bumptech.glide:glide:4.16.0"
    api "jp.wasabeef:glide-transformations:2.0.1"
    api "com.google.code.gson:gson:2.10.1"
    api "com.github.franmontiel:PersistentCookieJar:v1.0.1"

    //tools
    api "com.orhanobut:logger:2.2.0"
    api 'androidx.multidex:multidex:2.0.1'
    api "com.blankj:utilcodex:1.31.0"
}
